/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Ankush
 */
public class AdvSearch extends javax.swing.JFrame {

    /**
     * Creates new form AdvSearch
     */
    
    String trID;
    public AdvSearch() {
        System.out.println("in const adv");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mood");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(50, 60, 120, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Speed");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(50, 120, 130, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Genre");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(50, 90, 110, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(350, 130, 150, 29);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(350, 270, 150, 28);

        jButton1.setText("GET TYPES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 90, 140, 23);

        jButton2.setText("SHOW TRACKS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 230, 150, 23);

        jButton3.setText("GO TO TRACK PAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 370, 129, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicm/index2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 190, 322, 177);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FAST SORT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 20, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        // TODO add your handling code here: mood
//        System.out.println("in 1 r adv");
//        try
//        {
//            String sql="Select name from mood;";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//            jComboBox1.removeAllItems();
//            while(rs.next()) {
//                jComboBox1.addItem(rs.getString("name"));
//            }
//        }
//        catch(Exception e)
//        {
//            e.printStackTrace();
//        }
//        
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        
// TODO add your handling code here

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
//try
//        {
//            String sql="Select name from genre;";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//              
//            jComboBox1.removeAllItems();
//            while(rs.next()) {
//               jComboBox1.addItem(rs.getString("name")); 
//            }
//        }
//        catch(Exception e)
//        {
//            e.printStackTrace();
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
       
//jComboBox1.removeAllItems();
//            
//               jComboBox1.addItem("slow walk");
//                jComboBox1.addItem("brisk walk");
//                jComboBox1.addItem("jogging");
//                 jComboBox1.addItem("running");
//                  jComboBox1.addItem("sprint");
//             jComboBox1.addItem("marathon");
//        
//        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
//        if(jRadioButton1.isSelected()==true) 
//        try
//        {
//             String sql="Select tracks.name as nn from tracks,mood where mood.mood_id = tracks.mood_id and mood.name = '"+jComboBox1.getSelectedItem()+"';";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//            jComboBox2.removeAllItems();
//            while(rs.next()) {
//                 jComboBox2.addItem(rs.getString("nn"));
//            }
//        }
//        catch(Exception e)
//        {
//          e.printStackTrace();
//        }
//         if(jRadioButton3.isSelected()==true)
//         {
//             try
//        {
//             String sql="Select tracks.name as nn from tracks,genre where genre.genre_id=tracks.genre_id and genre.name='"+jComboBox1.getSelectedItem()+"';";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//jComboBox2.removeAllItems();
//            while(rs.next()) {
//                 jComboBox2.addItem(rs.getString("nn"));
//            }
//        }
//        catch(Exception e)
//        {
//          e.printStackTrace();
//        } 
//         }
//         if(jRadioButton2.isSelected()==true)
//         {
//             try
//        {
//             String sql="Select name from tracks where speed='"+jComboBox1.getSelectedItem()+"';";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//jComboBox2.removeAllItems();
//            while(rs.next()) {
//                 jComboBox2.addItem(rs.getString("name"));
//            }
//        }
//        catch(Exception e)
//        {
//          e.printStackTrace();
//        } 
       //  }
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here: refer track
        
//         try
//            {
//             String sql="Select track_id from tracks where name ='"+jComboBox2.getSelectedItem()+"';";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//            jComboBox2.removeAllItems();
//            while(rs.next()) {
//                 trID = rs.getInt("track_id");
//            }
//            this.dispose();
//            new track(trID).setVisible(true);
//        }
//        catch(Exception e)
//        {
//          e.printStackTrace();
//        } 
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: get teack
        if(jRadioButton1.isSelected())
        {
            try
        {
            String sql="Select name from mood;";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            jComboBox1.removeAllItems();
            while(rs.next()) {
                jComboBox1.addItem(rs.getString("name"));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
            
        }
        if(jRadioButton3.isSelected())
        {
            try
        {
            String sql="Select name from genre;";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
              
            jComboBox1.removeAllItems();
            while(rs.next()) {
               jComboBox1.addItem(rs.getString("name")); 
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }    
        }
        if(jRadioButton2.isSelected())
        {
            jComboBox1.removeAllItems();
            
               jComboBox1.addItem("slow walk");
                jComboBox1.addItem("brisk walk");
                jComboBox1.addItem("jogging");
                 jComboBox1.addItem("running");
                  jComboBox1.addItem("sprint");
             jComboBox1.addItem("marathon");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(jRadioButton1.isSelected()==true) 
        try
        {
             String sql="Select tracks.name as nn from tracks,mood where mood.mood_id = tracks.mood_id and mood.name = '"+jComboBox1.getSelectedItem()+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            jComboBox2.removeAllItems();
            while(rs.next()) {
                 jComboBox2.addItem(rs.getString("nn"));
            }
        }
        catch(Exception e)
        {
          e.printStackTrace();
        }
         if(jRadioButton3.isSelected()==true)
         {
             try
        {
             String sql="Select tracks.name as nn from tracks,genre where genre.genre_id=tracks.genre_id and genre.name='"+jComboBox1.getSelectedItem()+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
jComboBox2.removeAllItems();
            while(rs.next()) {
                 jComboBox2.addItem(rs.getString("nn"));
            }
        }
        catch(Exception e)
        {
          e.printStackTrace();
        } 
         }
         if(jRadioButton2.isSelected()==true)
         {
             try
        {
             String sql="Select name from tracks where speed='"+jComboBox1.getSelectedItem()+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
jComboBox2.removeAllItems();
            while(rs.next()) {
                 jComboBox2.addItem(rs.getString("name"));
            }
        }
        catch(Exception e)
        {
          e.printStackTrace();
        } 
         } // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try
            {
             String sql="Select track_id from tracks where name ='"+jComboBox2.getSelectedItem()+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            jComboBox2.removeAllItems();
            while(rs.next()) {
                trID = rs.getString("track_id");
            }
            this.dispose();
            new track(trID).setVisible(true);
        }
        catch(Exception e)
        {
          e.printStackTrace();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
