/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ankush
 */
public class group extends javax.swing.JFrame {

    /**
     * Creates new form group
     */
    
    String gID;
    String artistlist[] = new String[20];
    
    public group() {
        initComponents();
        this.gID = "1";
        viewGroup(gID);
    }

    public group(String gID) {
        initComponents();
        this.gID = gID;
        viewGroup(gID);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Group");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 64, 31);

        jLabel2.setText("Begin Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 80, 94, 23);

        jLabel3.setText("End Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 120, 98, 23);

        jLabel4.setText("No of member");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 150, 94, 28);

        jLabel5.setText("Members:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 190, 47, 14);

        jLabel6.setText("NAme");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 40, 119, 22);

        jButton1.setText("BACK TO SEARCH PAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 300, 290, 23);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 210, 120, 20);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 230, 120, 20);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 250, 80, 20);

        jLabel10.setText("Tracks:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 190, 50, 14);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 220, 70, 20);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(400, 260, 100, 20);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(410, 300, 80, 20);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 270, 90, 20);

        jLabel15.setText("Begin Date:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(270, 80, 100, 14);

        jLabel16.setText("End date:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(290, 120, 80, 14);

        jLabel17.setText("Number of members:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(240, 160, 170, 14);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicm/imagesrr.jpg"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, -30, 400, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: search
        this.dispose();
        new search().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void viewGroup(String gID){
        //group
        try {
            String sql="Select * from groups where g_id = '"+gID+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while(rs.next()) {
                jLabel6.setText(rs.getString("name"));
                jLabel2.setText(rs.getString("begin_date"));
                jLabel3.setText(rs.getString("end_date"));
                jLabel4.setText(Integer.toString(rs.getInt("no_of_members")));
                System.out.println(rs.getString("begin_date"));
                System.out.println(rs.getString("end_date"));
            }
        }catch (Exception e){
            System.out.println("error");
            e.printStackTrace();
        }
        
        //track
        try {
            String sql="Select name from tracks where g_id = '"+gID+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            int i=0;
            while(rs.next()) {
                artistlist[i++] = rs.getString("name");
                System.out.println("track - " + rs.getString("name"));
            }
             if(i>3){
                i=3;
            }
            switch(i){
                case 3:
                    jLabel13.setText(artistlist[--i]);
                case 2:
                    jLabel12.setText(artistlist[--i]);
                case 1:
                    jLabel11.setText(artistlist[--i]);
            }
        }catch (Exception e){
            System.out.println("error");
            e.printStackTrace();
        }
        
        //member
        try {
            String sql="Select name from artist where g_id = '"+gID+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            int i=0;
            while(rs.next()) {
                artistlist[i++] = rs.getString("name");
                System.out.println("track - " + rs.getString("name"));
            }
            
             if(i>4){
                i=4;
            }
            switch(i){
                case 4:
                    jLabel14.setText(artistlist[--i]);
                case 3:
                    jLabel9.setText(artistlist[--i]);
                case 2:
                    jLabel8.setText(artistlist[--i]);
                case 1:
                    jLabel7.setText(artistlist[--i]);
            }
        }catch (Exception e){
            System.out.println("error");
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new group().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
