/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package musicm;


import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ankush
 */
public class search extends javax.swing.JFrame {

    String type;
    String pk;
    String strList[] = new String[50];
    String table;
    String sql;
    String pkValue;
   // int userID;
    
    /** Creates new form m1 */
    public search() {
        initComponents();
    }
    
//    public search(int uID) {
//        initComponents();
//        this.userID = userID;
//        System.out.println(userID);
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jButton2.setText("Go");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 200, 140, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("MUSIC DATABASE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 170, 35);

        jLabel3.setText("search by");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 99, 100, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Artist", "Album", "Track", "Group" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 96, 170, 20);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(160, 142, 170, 28);

        jLabel1.setText("Select");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 149, 70, 14);

        jButton3.setText("Adv Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 260, 180, 23);

        jToggleButton1.setText("Get statistics");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(110, 260, 180, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicm/index23.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 0, 250, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getValue(String type){
        try {
            
        switch(type){
            
            case "Track":
                pk = "teack_id";
                table = "tracks";
                sql="Select name from tracks;";
                break;
            case "Artist":
                pk = "artist_id";
                table = "artist";
                sql= "Select name from artist;";
                break;
            case "Album":
                pk = "album_id";
                table = "album";
                sql="Select name from album;";
                break;
            case "Group":
                pk = "g_id";
                table = "groups";
                sql="Select name from groups;";
                break;
            case "Area":
                pk = "area_id";
                table = "area";
                sql="Select name from area;";
                break;
          
            default:
                pk = "teack_id";
                table = "tracks";
                sql="Select name from tracks;";
                break;
        }

        //album
        
            System.out.println("sql -> " + sql);
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            jComboBox2.removeAllItems();
            
            while(rs.next()) {
                jComboBox2.addItem(rs.getString("name"));
            }
        }catch (Exception e){
            //System.out.println("error");
            e.printStackTrace();
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  // TODO add your handling code here:  go
        String name = (String)jComboBox2.getSelectedItem();
        System.out.println("type :- "+ type);
        switch(type){
            case "Track":
                pk = "track_id";
                table = "tracks";
                System.out.println("inside 1 try");
                break;
            case "Artist":
                pk = "artist_id";
                table = "artist";
                break;
            case "Album":
                pk = "album_id";
                table = "album";
                break;
            case "Group":
                pk = "g_id";
                table = "groups";
                break;
        }
        try {
            System.out.println("pk - "+ pk + " table "+ table+" name  "+ name);
            
            String sql="Select "+pk+" from "+table+" where name = '"+name+"';";
            System.out.println(sql);
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                pkValue = rs.getString(pk);
            }
            
        }catch (Exception e){
            System.out.println("error");
            e.printStackTrace();
        }
        System.out.println("pk = "+pkValue);
        switch(type){
          case "Artist":
              this.dispose();
              new artist(pkValue).setVisible(true);
              break;
          case "Track":
              //System.out.println(userID);
              this.dispose();
              //new track(Integer.parseInt(pkValue)).setVisible(true);
              new track(pkValue).setVisible(true);
              break;
          case "Album":
              this.dispose();
              new album(pkValue).setVisible(true);
              break;
          case "Group":
              this.dispose();
              new group(pkValue).setVisible(true);
              break;
          } 
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
            
      type = (String)jComboBox1.getSelectedItem();
      getValue(type);
    
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:  type
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: adv searcg
        
        try{
        this.dispose();
        new AdvSearch().setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        new extra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
