/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicm;
import java.sql.*;
import java.awt.Desktop;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankush
 */
public class track extends javax.swing.JFrame {

    /**
     * Creates new form track
     */
    
    //int trackID;
    String trackID;
    String albumID;
    String yt;
    int moodID;
    int genreID;
    boolean flag;
    boolean flag2;
    int userID = 2;
    
    Desktop d=Desktop.getDesktop();
    
    public track() {
        initComponents();
        this.trackID = "015021a9-2621-4593-b82d-f1f28bdf440a";
        viewTrack(trackID);
    }
    //public track(int trackID) {
    public track(String trackID) {
        initComponents();
        this.trackID = trackID;
        flag=true;
        flag2=true;
        viewTrack(trackID);
    }
//    public track(int trackID,int userID) {
//        initComponents();
//        this.trackID = trackID;
//        this.userID = userID;
//        viewTrack(trackID);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Track");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(281, 11, 83, 39);

        jLabel2.setText("name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 70, 160, 28);

        jLabel3.setText("length");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 100, 69, 28);

        jLabel5.setText("release yr");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 140, 69, 25);

        jLabel6.setText("language");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 180, 68, 23);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 228, 58, 24);

        jLabel8.setText("mood");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 70, 140, 28);

        jLabel9.setText("genre");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 120, 140, 14);

        jButton1.setText("Listen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 260, 160, 23);

        jButton2.setText("back to search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 330, 170, 23);

        jButton3.setText("Add to fav");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 260, 160, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 163, 249, 401);

        jLabel10.setText("Name :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(14, 80, 90, 14);

        jLabel11.setText("Length:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 110, 90, 14);

        jLabel4.setText("Release year:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 130, 14);

        jLabel12.setText("language:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 180, 120, 14);

        jLabel13.setText("Mood:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 80, 110, 14);

        jLabel14.setText("Genre:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(380, 120, 110, 14);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicm/images22.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(70, 340, 350, 240);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 170, 100, 30);

        jButton4.setText("change language");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 220, 180, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  you tube
        try{
        d.browse(new URI("https://www.youtube.com/watch?v="+yt));
        }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: search
        this.dispose();
        new search().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: fav
        try{
            
            String sql2="select name from favourite f,tracks t where f.track_id=t.track_id and uID = '"+userID+"';";
                    
                    Class.forName("com.mysql.jdbc.Driver");
                    //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
                    Statement stmt1=con.createStatement();
                    ResultSet rs=stmt1.executeQuery(sql2);
                    if(flag2==true){
                    while(rs.next())
                    {
                        String nm=rs.getString("name");
                        Object[] row = {nm};
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        jTable1.setModel(model);
                        model.addRow(row);
        
                    }
                    flag2=false;}
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        try {
            if (flag==true){
            String sql2="insert into favourite(track_id,uid) values('"+trackID+"','"+userID+"')";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt1=con.createStatement();
            stmt1.executeUpdate(sql2);
            System.out.println("success inserting to favourite");
            flag=false;
            }}
        catch(Exception e){
                    e.printStackTrace();
                }
   
        
        
        
        
        try {
                    String sql2="exec [test7] '"+trackID+"','"+userID+"';";
                    
                    Class.forName("com.mysql.jdbc.Driver");
                    //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
                    Statement stmt1=con.createStatement();
                    stmt1.executeUpdate(sql2);
                    System.out.println("success");
                }catch(Exception e){
                    e.printStackTrace();
                }
        
//         try {
//                    String sql3="exec [test10]";
//                    
//                    Class.forName("com.mysql.jdbc.Driver");
//                    Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//                    Statement stmt2=con.createStatement();
//                    
//                    ResultSet rs=stmt2.executeQuery(sql3);
//                    String nm=rs.getString("nm1");
//                    Object[] row = { nm};
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//    jTable1.setModel(model);
//        
//        
//        model.addRow(row);
//                }catch(Exception e){
//                    e.printStackTrace();
//                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           try { String lang=jTextField1.getText();
            //String lang="spanish";
            String query="UPDATE tracks SET language='"+lang+"' WHERE track_id='"+trackID+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.executeUpdate();
            jLabel6.setText(lang);
           }
           catch (Exception e){
            System.out.println("error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
        
    public void viewTrack(String trackID){
        //area
        try {
            
            String sql="Select * from tracks where track_id='"+trackID+"';";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");

            //
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while(rs.next()) {
                jLabel2.setText(rs.getString("name"));
                jLabel3.setText(rs.getString("length"));
                yt = rs.getString("youtube_id");//jLabel4.setText();
                jLabel5.setText(rs.getString("release_yr"));
                jLabel6.setText(rs.getString("language"));
                moodID = rs.getInt("mood_id");//jLabel8.setText();
                genreID = rs.getInt("genre_id");//jLabel9.setText();
                //albumID = rs.getString("album_id");
              // System.out.println("userID" + userID);
            }
        }catch (Exception e){
            System.out.println("error");
            e.printStackTrace();
        }
        
        
//        try {
//            String sql="Select  from tracks where track_id='"+trackID+"';";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//
//            while(rs.next()) {
//            }
//        }catch (Exception e){
//            System.out.println("error");
//            e.printStackTrace();
//        }
        
//        System.out.println("album =  [" +albumID);
//        if(!albumID.equals("-1")){
//        //album
//        try {
//            String sql="Select name from album where album_id='"+albumID+"';";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
//            Statement stmt=con.createStatement();
//            ResultSet rs = stmt.executeQuery(sql);
//
//            while(rs.next()) {
//                jLabel7.setText(rs.getString("name"));
//            }
//        }catch (Exception e){
//            System.out.println("error");
//           e.printStackTrace();
//        }
//        }else{
//            jLabel7.setText("-----");
//        }
        
        //mood
        try {
            String sql="Select name from mood where mood_id= "+moodID+";";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while(rs.next()) {
                jLabel8.setText(rs.getString("name"));
            }
        }catch (Exception e){
            System.out.println("error");
           e.printStackTrace();
        }
        
        //gerne
        try {
            String sql="Select name from genre where genre_id= "+genreID+";";
            Class.forName("com.mysql.jdbc.Driver");
            //Connection con= (Connection) DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=music;user=root;password=dbpass");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/music??autoReconnect=true&useSSL=false"+"&user=root&password=dbpass");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while(rs.next()) {
                jLabel9.setText(rs.getString("name"));
            }
        }catch (Exception e){
            System.out.println("error");
           e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new track().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
